spring:
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      schema-locations:
        - classpath:sql/schema.sql
      data-locations:
        - classpath:sql/data.sql
  h2:
    console:
      enabled: true